version: '3.8'

services:

  
  # CONTENEDOR 1: Aplicación Flask (Python)
  
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: flask_app
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=db
      - DB_NAME=appdb
      - DB_USER=admin
      - DB_PASSWORD=admin123
    depends_on:
      db:
        condition: service_healthy
    networks:
      - red_integracion
    restart: on-failure


  # CONTENEDOR 2: Base de datos PostgreSQL
 
  db:
    image: postgres:15-alpine
    container_name: postgres_db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=appdb
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d appdb"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - red_integracion

  # CONTENEDOR 3: Jenkins CI/CD
 
jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins_ci
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - red_integracion
    restart: unless-stopped

networks:
  red_integracion:
    driver: bridge

volumes:
  postgres_data:
  jenkins_home: